#workflow
name: ci
on:
  push:
    branches: [develop]
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: 'npm'
       
    